In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr * 2)


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr )


[1 2 3 4]


In [7]:
print("zeroes",np.zeros(5))
print("ones",np.ones(3))
print("full",np.full(4,7))

zeroes [0. 0. 0. 0. 0.]
ones [1. 1. 1.]
full [7 7 7 7]


In [9]:
print("Arange 1–20:", np.arange(1, 21))

Arange 1–20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
print("license 1-10",np.linspace(0,1,10))

license 1-10 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
print("identity matrix:",np.eye(3))

identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
print("shape",arr.shape,"size",arr.size)

shape (4,) size 4


In [17]:
print(arr.dtype)

int64


In [18]:
print("first",arr[0],"last",arr[-1],"middle",arr[len(arr)//2])

first 1 last 4 middle 3


In [20]:
arr2 = np.arange(10)
print("First five:", arr2[:5])

First five: [0 1 2 3 4]


In [21]:
arr3 = np.arange(12).reshape(3,4)
print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
print(arr3.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
print(arr2+np.arange(10,20))

[10 12 14 16 18 20 22 24 26 28]


In [24]:
print(arr2*5)

[ 0  5 10 15 20 25 30 35 40 45]


In [28]:
print("sum",arr2.sum(),"mean",arr2.mean(),"max",arr2.max(),"min",arr2.min)

sum 45 mean 4.5 max 9 min <built-in method min of numpy.ndarray object at 0x000002B3FF74F9F0>


In [30]:
unsort=np.array([5,4,8,1,0])
print(np.sort(unsort))


[0 1 4 5 8]


In [31]:
print(np.random.randint(1,100,size=5))

[70 89 92 55 18]


In [32]:
print(np.unique(np.array([1,1,3,4,5,5,5,67,7])))

[ 1  3  4  5  7 67]


In [34]:
print(arr3.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [35]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [36]:
marks=np.array([78,62,75,65,90,78])
print(marks)
print(marks.mean())
print(marks.max())
print(marks.min())
print(marks[marks>80])

[78 62 75 65 90 78]
74.66666666666667
90
62
[90]
